// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9tBgVRjtQpfLLLF5yXm2d1cBfNrwT_Yk',
    appId: '1:924546758982:web:8264bcc832c2e23cff4d47',
    messagingSenderId: '924546758982',
    projectId: 'fir-cloud-messaging-65115',
    authDomain: 'fir-cloud-messaging-65115.firebaseapp.com',
    storageBucket: 'fir-cloud-messaging-65115.firebasestorage.app',
    measurementId: 'G-2DY6BQX864',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeAxz6XFz-Q0OFudEWAktVul3NEJc3bpg',
    appId: '1:924546758982:android:ae02ceea45b2194fff4d47',
    messagingSenderId: '924546758982',
    projectId: 'fir-cloud-messaging-65115',
    storageBucket: 'fir-cloud-messaging-65115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDde-HEAMuhfSSsJB2QDYXdxLiiSegRop0',
    appId: '1:924546758982:ios:f1cc9d1ada413a4cff4d47',
    messagingSenderId: '924546758982',
    projectId: 'fir-cloud-messaging-65115',
    storageBucket: 'fir-cloud-messaging-65115.firebasestorage.app',
    iosBundleId: 'com.example.ica17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDde-HEAMuhfSSsJB2QDYXdxLiiSegRop0',
    appId: '1:924546758982:ios:f1cc9d1ada413a4cff4d47',
    messagingSenderId: '924546758982',
    projectId: 'fir-cloud-messaging-65115',
    storageBucket: 'fir-cloud-messaging-65115.firebasestorage.app',
    iosBundleId: 'com.example.ica17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9tBgVRjtQpfLLLF5yXm2d1cBfNrwT_Yk',
    appId: '1:924546758982:web:d1c69770911e8ebbff4d47',
    messagingSenderId: '924546758982',
    projectId: 'fir-cloud-messaging-65115',
    authDomain: 'fir-cloud-messaging-65115.firebaseapp.com',
    storageBucket: 'fir-cloud-messaging-65115.firebasestorage.app',
    measurementId: 'G-17ZKQ7GEC5',
  );
}
